[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
clickcrate_program = "8haS17iUkRL1aMchExXTcLS5J8iHwupN9gWWRNLD9q3v"

[programs.localnet]
clickcrate_program = "8haS17iUkRL1aMchExXTcLS5J8iHwupN9gWWRNLD9q3v"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/solana-wallets/clickcrate-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
